### ISSUE TITLE
Mira charger issue

### ISSUE THREAD

**Issue by nilsbore** [strands-project/scitos_drivers#47]
Since this morning we've started getting the following messages from MIRA:

RNING ] 2013-Nov-05 12:36:23.189397 /robot/#Charger_7ebd59b2-67ab-48d1-8f94-eb5745275d4e : Booting up
[ WARN] [1383651384.251891514]: (MIRA) /robot/#Charger_7ebd59b2-67ab-48d1-8f94-eb5745275d4e : Booting up
[WARNING ] 2013-Nov-05 12:36:24.251775 /robot/#Charger_7ebd59b2-67ab-48d1-8f94-eb5745275d4e : Booting up
[ WARN] [1383651385.304280096]: (MIRA) /robot/#Charger_7ebd59b2-67ab-

This seems to affect the base, and even when driving the robot around with the joystick the base gets stuck for a few seconds every now and then, after which it resumes motion.

Any ideas @cburbridge @chmartin21? Has anyone seen this before?

**Comment by RaresAmbrus** [comment]
We've experimented with a few things and we still get the same error. The problem is that one of the modules initialized by the mira framework, the charger module, does not get initialized properly; its status oscillates between booting up and operational. We're getting the same readings through MIRA's software - miracenter. We've also tried updating the MIRA packages without any luck. However, when placed on the charging station the robot is able to charge successfully.

If anyone has any ideas about how to disable this charger module altogether then that could be a short term solution, however, as far as I can tell, when disabling the charger module directly from miracenter the whole robot shuts down (the charger module is responsible for the battery somehow as well). 

A ticket has been created with MetraLabs and we'll wait for some support from their side, but in the meantime our robot is out of commission until we can find some solution to this issue.

**Comment by chmartin21** [comment]
The "Booting up" message indicates, that the charger (which is also the power supply unit) of the robot restarts its CAN-Bus interface. The charger provides an internal robot timer, which is used of synchronization of the different CAN bus modules. Furthermore, the motor controller (which is part of the MCU - main control unit) uses this clock to realize a watchdog behaviour. Only velocity commands (from the PC) with a valid time-stamp will be executed. This is some kind of safety feature. Due to the restart of the CAN bus device of the charger, the robot clock is reseted and the next velocity command from the PC will have an invalid time-stamp. This will cause an immediate stop of the motors and the robot gets stuck.

Did you connect some new hardware to the robot? Did you some kind of hardware modification?

I will discuss this issue with our hardware engineers. It might be necessary to send the robot back to us for error diagnostics and repair. We will let you know.

**Comment by RaresAmbrus** [comment]
Hi Christian,

Thanks for the update. We have added a second camera, from Primesense, but I doubt that's causing the issue, because the robot has been running with it for some time now. Other than that we haven't made any modifications. 

Also if it will help you we can set the robot on a public IP so you can ssh to it and debug it "live".

**Comment by RaresAmbrus** [comment]
@chmartin21 
We've scheduled a demo of the robot next Friday, and we need to give an update tomorrow on whether we will be able to carry out the demo or not, thus we know asap whether the robot can be fixed quickly. It's impossible to teleoperate it in the current condition, as the CAN bus keeps restarting and this interferes with the motion of the robot. 
If possible can you please ask someone to look into this and let us know as soon as possible what steps we have to take to debug the issue further (loose connections, replacing the harddrive, etc.) or otherwise to take a look via ssh at the robot?
Thanks!

**Comment by chmartin21** [comment]
@RaresAmbrus
On thing, that you can do is to read out the persistent error memory of the robot. For that, you have to start miracenter with a configuration, which contains the SCITOS driver. Then go to the RPC console and execute the following RPC: /robot/Robot.savePersistentErrors("errors_2013-mm-dd.txt"). Depending on the number of errors this operation may take some time. Afterwards you can find the error file in the current working directory.

**Comment by chmartin21** [comment]
@RaresAmbrus
For additional debugging it would be helpful for us, if you could record a tape with the incoming CAN messages. That can be done in the following way:
- Start miracenter with the configuration /opt/MIRA-commerical/domains/can/CANDriver/etc/CANDriver.xml
- Open the log file recorder, add the channel IncomingCAN 
- Record a log file of 10-20sec
  Please send us the log file afterwards.

**Comment by nilsbore** [comment]
So our robot is going in for repairs tomorrow. There seems to be something wrong with the connection between the PC and the basis electronics of the platform. Unfortunately, this probably means that we're out of the marathon. I will keep this issue open until we have a working robot again.

**Comment by nilsbore** [comment]
We were planning on joining the marathon late but the robot hasn't returned yet (it should arrive today or tomorrow), so there will be little time for us to set something up. We will try to beat the best mileage next week though=P.

**Comment by nilsbore** [comment]
Ok, this was fixed and I think the cause was us messing around with the display. Closing.
